import { jsPDF } from "jspdf";
import autoTable from "jspdf-autotable";
import { UACE_WPF_SECTIONS, UCE_WPF_SECTIONS } from "../constants/wpf-schedules";
import { StudentRecord } from "../components/auth-context";
import { toast } from "sonner";

export const generateWPF_PDF = (
  level: "UCE" | "UACE",
  schoolContext: {
    name: string;
    code: string;
    district: string;
    zone: string;
    telephone: string;
    academicYear?: string;
    email?: string;
  },
  students: StudentRecord[]
) => {
  console.log("[WPF DEBUG] Starting PDF generation");
  console.log("[WPF DEBUG] Level:", level);
  console.log("[WPF DEBUG] School context:", schoolContext);
  console.log("[WPF DEBUG] Total students passed:", students.length);
  console.log("[WPF DEBUG] Student data sample:", JSON.stringify(students.slice(0, 2), null, 2));
  
  const sections = level === "UACE" ? UACE_WPF_SECTIONS : UCE_WPF_SECTIONS;
  const schoolStudents = students.filter(
    (student) => student.schoolCode === schoolContext.code && student.examLevel === level,
  );
  
  console.log("[WPF DEBUG] Filtered school students count:", schoolStudents.length);
  console.log("[WPF DEBUG] School students sample:", JSON.stringify(schoolStudents.slice(0, 2), null, 2));

  const pdf = new jsPDF({ orientation: "landscape", unit: "mm", format: "a4" });
  const pageWidth = pdf.internal.pageSize.getWidth();
  const pageHeight = pdf.internal.pageSize.getHeight();
  const margin = 8;
  const colGap = 2;
  const colWidth = (pageWidth - (margin * 2) - (colGap * 3)) / 4;
  const headerHeight = 35; // Total height used by header
  const footerHeight = 15; // Total height reserved for footer
  const maxTableHeight = pageHeight - footerHeight;

  let currentCol = 0;
  let currentY = headerHeight;

  const drawHeader = (doc: jsPDF, pageNum: number) => {
    let y = 12;
    doc.setFont("times", "bold");
    doc.setFontSize(16);
    doc.text("WAKISSHA JOINT MOCK EXAMINATIONS", margin, y);
    
    doc.setFontSize(14);
    const titleText = `WEEKLY PACKING FORM; ${level}`;
    doc.text(titleText, pageWidth / 2, y, { align: "center" });
    
    const yearText = `YEAR: ${schoolContext.academicYear ?? "2026"}`;
    doc.text(yearText, pageWidth - margin - 5, y, { align: "right" });
    
    y += 8;

    doc.setFontSize(9);
    doc.setFont("times", "bold");
    
    // Line 1: School Name, REF No, H/M Sign, Telephone
    const line1Y = y;
    doc.text("NAME OF SCHOOL:", margin, line1Y);
    doc.setFont("times", "normal");
    doc.text(schoolContext.name.toUpperCase(), margin + 30, line1Y);
    doc.line(margin + 30, line1Y + 1, margin + 110, line1Y + 1);

    doc.setFont("times", "bold");
    doc.text("REF No.:", margin + 115, line1Y);
    doc.setFont("times", "normal");
    doc.text(schoolContext.code, margin + 130, line1Y);
    doc.line(margin + 130, line1Y + 1, margin + 155, line1Y + 1);

    doc.setFont("times", "bold");
    doc.text("NAME & SIGNATURE OF H/M:", margin + 160, line1Y);
    doc.line(margin + 205, line1Y + 1, margin + 235, line1Y + 1);

    doc.setFont("times", "bold");
    doc.text("TELEPHONE:", margin + 240, line1Y);
    doc.setFont("times", "normal");
    doc.text(schoolContext.telephone, margin + 262, line1Y);
    doc.line(margin + 262, line1Y + 1, margin + 285, line1Y + 1);

    y += 7;

    // Line 2: District, Zone, Contact Email
    const line2Y = y;
    doc.setFont("times", "bold");
    doc.text("DISTRICT:", margin, line2Y);
    doc.setFont("times", "normal");
    doc.text(schoolContext.district.toUpperCase(), margin + 18, line2Y);
    doc.line(margin + 18, line2Y + 1, margin + 85, line2Y + 1);

    doc.setFont("times", "bold");
    doc.text("ZONE:", margin + 95, line2Y);
    doc.setFont("times", "normal");
    doc.text(schoolContext.zone.toUpperCase(), margin + 107, line2Y);
    doc.line(margin + 107, line2Y + 1, margin + 160, line2Y + 1);

    doc.setFont("times", "bold");
    doc.text("CONTACT EMAIL ADDRESS:", margin + 170, line2Y);
    doc.setFont("times", "normal");
    doc.text(schoolContext.email || "", margin + 218, line2Y);
    doc.line(margin + 218, line2Y + 1, margin + 285, line2Y + 1);
  };

  const drawFooter = (doc: jsPDF) => {
    const fY = pageHeight - 12;
    doc.setFont("times", "bold");
    doc.setFontSize(8);
    doc.text("INSTRUCTIONS: You are required to fill in the total number of candidates registered for each paper done at your school for sections AC - A3 and submit.", margin, fY);

    doc.setFont("times", "italic");
    doc.setFontSize(7);
    doc.text(`Generated by WAKISSHA Management System | ${new Date().toLocaleString()}`, margin, pageHeight - 5);
  };

  // Initial Draw
  drawHeader(pdf, 1);
  drawFooter(pdf);

  sections.forEach((section, sectionIdx) => {
    // Process rows to add rowSpan for identical dates
    const tableBody: any[] = [];
    let i = 0;
    while (i < section.rows.length) {
      const row = section.rows[i];
      let rowSpan = 1;
      let j = i + 1;
      while (j < section.rows.length && section.rows[j].date === row.date) {
        rowSpan++;
        j++;
      }

      const processRow = (r: typeof row) => {
        const targetPaperNum = r.paper;
        let candidateCount = 0;
        
        for (const student of schoolStudents) {
          for (const subj of student.subjects ?? []) {
            const subjCode = (subj.subjectStandardCode || subj.subjectCode || "").trim().toUpperCase();
            const rowCodes = r.code.split("/").map((c: string) => c.trim().toUpperCase());
            
            const codeMatch = rowCodes.some((c: string) => 
              subjCode === c || 
              subjCode.includes(c) || 
              c.includes(subjCode)
            );
            
            if (!codeMatch) continue;

            const paperStr = String(subj.paper || "").toUpperCase();
            const paperMatchResult = paperStr.match(/\d+/);
            if (!paperMatchResult) continue;
            
            const studentPaperNum = parseInt(paperMatchResult[0], 10);
            
            if (studentPaperNum === targetPaperNum) {
              candidateCount++;
              break;
            }
          }
        }
        
        console.log(`[WPF DEBUG] Row: ${r.code}/${r.paper} ${r.subjectName}, Count: ${candidateCount}`);
        return candidateCount.toString();
      };

      tableBody.push([
        { content: row.date.replace(/\/\d{4}/, ''), rowSpan: rowSpan, styles: { valign: 'middle', halign: 'left' } },
        `${row.code}/${row.paper} ${row.subjectName}`,
        processRow(row)
      ]);

      for (let k = 1; k < rowSpan; k++) {
        const nextRow = section.rows[i + k];
        tableBody.push([
          `${nextRow.code}/${nextRow.paper} ${nextRow.subjectName}`,
          processRow(nextRow)
        ]);
      }
      i += rowSpan;
    }

    // Estimate height: header (10mm) + rows (approx 4.5mm each for small font)
    const estimatedHeight = 12 + (tableBody.length * 4.2);
    
    // Check if section fits in current column
    if (currentY + estimatedHeight > maxTableHeight) {
      currentCol++;
      if (currentCol > 3) {
        pdf.addPage();
        drawHeader(pdf, pdf.internal.getNumberOfPages());
        drawFooter(pdf);
        currentCol = 0;
      }
      currentY = headerHeight;
    }

    const startX = margin + (currentCol * (colWidth + colGap));

    autoTable(pdf, {
      startY: currentY,
      margin: { left: startX, right: pageWidth - (startX + colWidth) },
      tableWidth: colWidth,
      head: [
        [
          { content: "Date", styles: { halign: 'center', cellWidth: 15 } },
          { content: `${section.id}\nSubject/Paper`, styles: { halign: 'center' } },
          { content: "No. of\nCandidates\nregistered\nfor paper", styles: { halign: 'center', cellWidth: 18 } }
        ]
      ],
      body: tableBody,
      theme: "grid",
      pageBreak: 'avoid', // Try to keep section together
      styles: {
        font: "times",
        fontSize: 7.5,
        cellPadding: 0.8, // Reduced padding to fit more
        lineColor: [0, 0, 0],
        lineWidth: 0.1,
        textColor: [0, 0, 0],
      },
      headStyles: {
        fillColor: [255, 255, 255],
        textColor: [0, 0, 0],
        fontStyle: "bold",
        lineWidth: 0.1,
        minCellHeight: 10, // Reduced from 12
      },
      columnStyles: {
        0: { cellWidth: 15 },
        1: { cellWidth: 'auto' },
        2: { cellWidth: 18, halign: "center" },
      },
      didDrawPage: (data) => {
        // This prevents automatic page breaks from messing up our layout
        // if jspdf-autotable decides to break anyway.
      }
    });

    currentY = (pdf as any).lastAutoTable.finalY + 3; // Gap between sections
  });

  pdf.save(`WPF_${level}_${schoolContext.code}.pdf`);
  toast.success(`${level} Weekly Packing Form exported successfully`);
};
